### ISSUE TITLE
Broken on latest node version:- no member named 'ForceSet' in 'v8::Object'

### ISSUE THREAD

**Issue by sonicvision** [Jacse/react-native-app-intro-slider#102]
On trying to build on latest node version v11.10.0 I get the following error:-

n file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h../fsevents.cc::6:
112In file included from :../node_modules/nan/nan.h15::192 :
error../node_modules/nan/nan_maybe_43_inl.h: :no member named 'ForceSet' in 'v8::Object'
112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../fsevents.cc:6In file included from ../fsevents.cc:
:In file included from 6../node_modules/nan/nan.h:198:
:
In file included from ../node_modules/nan/nan_new.hIn file included from :189:
../node_modules/nan/nan.h../node_modules/nan/nan_implementation_12_inl.h::198337:
:In file included from 28../node_modules/nan/nan_new.h::189 warning:
: ../node_modules/nan/nan_implementation_12_inl.h'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]:
337:28: warning: 'New' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
  return v8::StringObject::New(value).As<v8::StringObject>();
                           ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8.h/Users/praveensahu/.node-gyp/11.10.0/include/node/v8.h::5241:35241::3: note : note: 'New' has been explicitly marked deprecated here'New' has been explicitly marked deprecated here

  V8_DEPRECATED(\"Use Isolate* version\",
  ^
  V8_DEPRECATED(\"Use Isolate* version\",
  ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8config.h:326:/Users/praveensahu/.node-gyp/11.10.0/include/node/v8config.h:32629:: note: 29expanded from macro 'V8_DEPRECATED':
 note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:911:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
In file included from ../fsevents.cc:      v8::Local<v8::String> string = from->ToString();6:

                                           ^../node_modules/nan/nan.h
:849:18/Users/praveensahu/.node-gyp/11.10.0/include/node/v8.h:: 2548warning:: 10'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
: note: 'ToString' has been explicitly marked deprecated here
    return node::MakeCallback(
                 ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
  inline V8_DEPRECATED(\"Use maybe version\", Local<String> ToString() const);
         ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8config.h:326:29:NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
 ^note
: expanded from macro 'V8_DEPRECATED'
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:921:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use Isolate* version\",
  ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:911:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString();
                                           ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED(\"Use maybe version\", Local<String> ToString() const);
         ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:921:27: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                          ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED(\"Use Isolate* version\",
  ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED(\"Use MakeCallback(..., async_context)\",
^
/Users/praveensahu/.node-gyp/11.10.0/include/node/node.h:91:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator

**Comment by Jacse** [comment]
Are you sure this is related to this component and not a different issue?

**Comment by sonicvision** [comment]
Well... May be it's not. Not sure actually. 
Just saw this on using this plugin. Did not dig deep.

**Comment by Jacse** [comment]
Well, I'll close the issue in that case - let me know if you're sure this is where the issue lies. For future reference, please make sure only to open bug reports when you are decently sure there is a bug.
